/* moonlitt — headless DAW engine.
 * C API, ABI draft 0.9 (frozen surface lands as 1.0).
 *
 * Conventions:
 *   - Fallible functions return MoonlittStatus: 0 = MOONLITT_OK,
 *     negative = MOONLITT_ERR_* class. The human-readable detail for the
 *     most recent failure on the calling thread comes from
 *     moonlitt_last_error_message() (borrowed pointer — do NOT free).
 *   - Functions documented as returning owned strings/buffers must be
 *     freed with moonlitt_free_string (strings).
 *   - Out-of-range arguments are rejected, never clamped.
 *   - One control thread per handle; the audio thread is internal.
 */

#ifndef MOONLITT_H
#define MOONLITT_H

/* Generated by cbindgen — do not edit by hand; edit crates/moonlitt-capi/src and regenerate. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI version, bumped by hand on every ABI-affecting change.
 * Draft surface is 0.9.x; the freeze tag will set 1.0.0.
 */
#define MOONLITT_ABI_MAJOR 0

#define MOONLITT_ABI_MINOR 9

#define MOONLITT_ABI_PATCH 0

/**
 * Opaque engine handle exposed to C callers.
 */
typedef struct EngineHandle EngineHandle;

/**
 * Opaque mixer handle for pre-building a mixer before creating a Runtime.
 */
typedef struct MixerHandle MixerHandle;

/**
 * Opaque runtime handle exposed to C callers.
 */
typedef struct RuntimeHandle RuntimeHandle;

/**
 * Status code returned by fallible moonlitt functions.
 * `0` = success; negative values classify the failure.
 */
typedef int32_t MoonlittStatus;

/**
 * Success.
 */
#define MOONLITT_OK 0

/**
 * An argument was null, out of range, or otherwise invalid.
 */
#define MOONLITT_ERR_INVALID_ARG -1

/**
 * The operation needs a loaded backend/resource that isn't there
 * (engine without a sound loaded, consumed engine handle, …).
 */
#define MOONLITT_ERR_NOT_LOADED -2

/**
 * The lock-free event queue to the audio thread is full; the event
 * was dropped. Retry on the next tick.
 */
#define MOONLITT_ERR_QUEUE_FULL -3

/**
 * Filesystem or device I/O failed.
 */
#define MOONLITT_ERR_IO -4

/**
 * The hosted plugin (VST3/CLAP) or soundfont rejected the operation.
 */
#define MOONLITT_ERR_PLUGIN -5

/**
 * State blob save/load failed (corrupt, wrong backend, version skew).
 */
#define MOONLITT_ERR_STATE -6

/**
 * An internal panic was caught at the FFI boundary.
 */
#define MOONLITT_ERR_PANIC -7

/**
 * The backend does not support this operation.
 */
#define MOONLITT_ERR_UNSUPPORTED -8

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Human-readable detail of the most recent failure on the calling
 * thread, or NULL if nothing failed yet.
 *
 * Ownership: borrowed from the library — do NOT free. Valid on the
 * calling thread until the next failing moonlitt call. Only meaningful
 * immediately after a call returned non-OK / NULL.
 */
const char *moonlitt_last_error_message(void);

/**
 * Packed ABI version: `(major << 16) | (minor << 8) | patch`.
 *
 * Bindings should check this at load time and refuse to run against an
 * incompatible major version.
 */
uint32_t moonlitt_abi_version(void);

/**
 * Diagnostics: deliberately panic inside the library so bindings can
 * verify the panic guard end-to-end (the call must return
 * `MOONLITT_ERR_PANIC` — never crash the process).
 */
MoonlittStatus moonlitt_debug_trigger_panic(void);

/**
 * Create a new engine handle with no backend loaded.
 *
 * * `sample_rate` — Hz, must be > 0 (typical: 44100 or 48000)
 * * `buffer_size` — frames per render block, must be > 0 (typical: 256)
 *
 * Returns an owned opaque pointer (free with `moonlitt_engine_destroy`),
 * or NULL with a last-error message if the configuration is invalid.
 */
struct EngineHandle *moonlitt_engine_create(int sample_rate, int buffer_size);

/**
 * Destroy an engine handle and its backend. Safe to call with NULL.
 * After this the pointer is dangling — do not use it again.
 */
void moonlitt_engine_destroy(struct EngineHandle *e);

/**
 * Load a plugin or soundfont; the format is detected from the file
 * extension (`.sf2` / `.vst3` / `.clap`). Replaces any backend that was
 * already loaded.
 *
 * Returns `MOONLITT_OK`, `MOONLITT_ERR_INVALID_ARG` (NULL handle/path),
 * `MOONLITT_ERR_IO` (file missing/unreadable) or `MOONLITT_ERR_PLUGIN`
 * (the file exists but the backend failed to initialise).
 */
MoonlittStatus moonlitt_engine_load(struct EngineHandle *e, const char *path);

/**
 * Drop the loaded backend (if any). Safe on NULL and on an engine with
 * nothing loaded; never fails.
 */
void moonlitt_engine_unload(struct EngineHandle *e);

/**
 * Returns 1 if a backend is loaded, 0 otherwise (including NULL handle).
 */
int moonlitt_engine_is_loaded(struct EngineHandle *e);

/**
 * Start a note.
 *
 * * `ch`   — MIDI channel, 0..=15
 * * `note` — MIDI note number, 0..=127 (60 = middle C)
 * * `vel`  — velocity, 0..=127 (0 is interpreted as note-off by MIDI
 *   convention; backends follow it)
 */
MoonlittStatus moonlitt_engine_note_on(struct EngineHandle *e, int ch, int note, int vel);

/**
 * Release a note. `ch` 0..=15, `note` 0..=127.
 */
MoonlittStatus moonlitt_engine_note_off(struct EngineHandle *e, int ch, int note);

/**
 * Send a MIDI control change. `ch` 0..=15, `cc` 0..=127, `val` 0..=127.
 * Common controllers: 1 = mod wheel, 7 = volume, 11 = expression,
 * 64 = sustain pedal.
 */
MoonlittStatus moonlitt_engine_cc(struct EngineHandle *e, int ch, int cc, int val);

/**
 * Send a pitch-bend. `ch` 0..=15, `val` -8192..=8191 (0 = centre).
 */
MoonlittStatus moonlitt_engine_pitch_bend(struct EngineHandle *e, int ch, int val);

/**
 * Switch program/patch on a channel. `ch` 0..=15, `prog` 0..=127.
 * For VST3 sampler-style plugins prefer `moonlitt_engine_load_preset`.
 */
MoonlittStatus moonlitt_engine_program_change(struct EngineHandle *e, int ch, int prog);

/**
 * Release every sounding note on every channel.
 */
MoonlittStatus moonlitt_engine_all_notes_off(struct EngineHandle *e);

/**
 * Render `frames` samples of audio into the caller's `left`/`right`
 * buffers (each must hold at least `frames` f32 values — the library
 * cannot verify this).
 *
 * With no backend loaded the buffers are filled with silence and
 * `MOONLITT_ERR_NOT_LOADED` is returned, so a lazy caller still gets
 * valid audio while an attentive one can detect the missing load.
 */
MoonlittStatus moonlitt_engine_render(struct EngineHandle *e,
                                      float *left,
                                      float *right,
                                      int frames);

/**
 * Set the backend's output volume. `volume` is linear gain (1.0 =
 * unity); NaN is rejected.
 */
MoonlittStatus moonlitt_engine_set_volume(struct EngineHandle *e, float volume);

/**
 * Scan the system plugin directories. Returns a JSON array
 * `[{"name","path","format"}, …]`.
 *
 * Ownership: the returned string is owned by the caller — free it with
 * `moonlitt_free_string`. Returns NULL on NULL handle.
 */
char *moonlitt_engine_scan_plugins(struct EngineHandle *e);

/**
 * List the loaded backend's presets as JSON `[{"id","name"}, …]`.
 * An empty list (`[]`) means the backend exposes no presets.
 *
 * Ownership: caller frees with `moonlitt_free_string`. Returns NULL
 * (with NOT_LOADED / INVALID_ARG detail) when no backend is loaded.
 */
char *moonlitt_engine_get_presets(struct EngineHandle *e);

/**
 * Load a preset by the id reported in `moonlitt_engine_get_presets`.
 */
MoonlittStatus moonlitt_engine_load_preset(struct EngineHandle *e, int id);

/**
 * Number of automatable parameters on the loaded backend (0 when
 * nothing is loaded or the handle is NULL).
 */
int moonlitt_engine_param_count(struct EngineHandle *e);

/**
 * All parameter metadata as JSON
 * `[{"id","name","group","min","max","default","step_count","flags"}, …]`.
 *
 * Ownership: caller frees with `moonlitt_free_string`. Returns NULL
 * when no backend is loaded.
 */
char *moonlitt_engine_param_info_json(struct EngineHandle *e);

/**
 * Current value of parameter `id`, or NaN when the handle/backend/id
 * is invalid (documented sentinel — check with `isnan`).
 */
double moonlitt_engine_get_param(struct EngineHandle *e, int id);

/**
 * Set parameter `id` to `value` (normalised to the range reported in
 * `moonlitt_engine_param_info_json`). NaN and negative ids are rejected.
 */
MoonlittStatus moonlitt_engine_set_param(struct EngineHandle *e, int id, double value);

/**
 * Human-readable display string for a parameter value (e.g. `"-6.0 dB"`).
 *
 * Ownership: caller frees with `moonlitt_free_string`. Returns NULL when
 * the handle/backend/id is invalid.
 */
char *moonlitt_engine_param_display(struct EngineHandle *e, int id, double value);

/**
 * Render a reference tone offline and measure its RMS level.
 *
 * * `program` — GM program (0 = piano), 0..=127
 * * `note` — MIDI note, 0..=127 (60 = C4)
 * * `velocity` — 1..=127
 * * `duration_ms` — render length, must be > 0
 *
 * Returns dBFS (negative). `-100.0` is the documented error/silence
 * sentinel; the detail is in `moonlitt_last_error_message()`.
 */
float moonlitt_engine_measure_rms(struct EngineHandle *e,
                                  int program,
                                  int note,
                                  int velocity,
                                  int duration_ms);

/**
 * Create a live-audio runtime from an engine handle.
 *
 * **Ownership**: the backend is consumed out of `engine_handle` only on
 * success. On failure (e.g. no audio output device) the backend is put
 * back, so the caller may retry or keep using the engine offline. The
 * (now empty) engine handle must still be destroyed eventually.
 *
 * Returns NULL + last-error on failure.
 */
struct RuntimeHandle *moonlitt_runtime_create(struct EngineHandle *engine_handle);

/**
 * Destroy a runtime handle: stops audio output and frees resources.
 * Safe to call with NULL.
 */
void moonlitt_runtime_destroy(struct RuntimeHandle *rt);

/**
 * Start the audio output stream (begin calling the audio device).
 */
MoonlittStatus moonlitt_runtime_start_audio(struct RuntimeHandle *rt);

/**
 * Pause the audio output stream (the device callback stops firing).
 */
MoonlittStatus moonlitt_runtime_stop_audio(struct RuntimeHandle *rt);

/**
 * Start a note. `ch` 0..=15, `note` 0..=127, `vel` 0..=127.
 */
MoonlittStatus moonlitt_runtime_note_on(struct RuntimeHandle *rt, int ch, int note, int vel);

/**
 * Note-on delayed by `delay_samples` frames for sample-accurate timing
 * (`delay_samples` >= 0; at 48 kHz one frame ≈ 21 µs).
 */
MoonlittStatus moonlitt_runtime_note_on_delayed(struct RuntimeHandle *rt,
                                                int ch,
                                                int note,
                                                int vel,
                                                int delay_samples);

/**
 * Release a note. `ch` 0..=15, `note` 0..=127.
 */
MoonlittStatus moonlitt_runtime_note_off(struct RuntimeHandle *rt, int ch, int note);

/**
 * Note-off delayed by `delay_samples` frames (>= 0).
 */
MoonlittStatus moonlitt_runtime_note_off_delayed(struct RuntimeHandle *rt,
                                                 int ch,
                                                 int note,
                                                 int delay_samples);

/**
 * Send a MIDI control change. `ch` 0..=15, `cc` 0..=127, `val` 0..=127.
 * Common controllers: 1 = mod wheel, 7 = volume, 11 = expression,
 * 64 = sustain pedal.
 */
MoonlittStatus moonlitt_runtime_cc(struct RuntimeHandle *rt, int ch, int cc, int val);

/**
 * Send a pitch-bend. `ch` 0..=15, `val` -8192..=8191 (0 = centre).
 */
MoonlittStatus moonlitt_runtime_pitch_bend(struct RuntimeHandle *rt, int ch, int val);

/**
 * Switch program/patch on a channel. `ch` 0..=15, `prog` 0..=127.
 */
MoonlittStatus moonlitt_runtime_program_change(struct RuntimeHandle *rt, int ch, int prog);

/**
 * Release every sounding note on every channel.
 */
MoonlittStatus moonlitt_runtime_all_notes_off(struct RuntimeHandle *rt);

/**
 * Set the source backend's output volume (linear gain, 1.0 = unity).
 */
MoonlittStatus moonlitt_runtime_set_volume(struct RuntimeHandle *rt, float volume);

/**
 * Set backend parameter `id` to `value` (f64, matching the engine-side
 * parameter precision).
 */
MoonlittStatus moonlitt_runtime_set_param(struct RuntimeHandle *rt, int id, double value);

/**
 * Set backend parameter `param_id` on one specific track.
 */
MoonlittStatus moonlitt_runtime_set_track_param(struct RuntimeHandle *rt,
                                                int track_id,
                                                int param_id,
                                                double value);

/**
 * Set parameter `param_id` on one insert effect of a track.
 */
MoonlittStatus moonlitt_runtime_set_insert_param(struct RuntimeHandle *rt,
                                                 int track_id,
                                                 int insert_id,
                                                 int param_id,
                                                 double value);

/**
 * Set parameter `param_id` on a send bus effect.
 */
MoonlittStatus moonlitt_runtime_set_send_bus_param(struct RuntimeHandle *rt,
                                                   int bus_id,
                                                   int param_id,
                                                   double value);

/**
 * Track fader volume (linear gain, 1.0 = unity).
 */
MoonlittStatus moonlitt_runtime_set_track_volume(struct RuntimeHandle *rt, int track_id, float vol);

/**
 * Track input trim in dB (0.0 = no trim).
 */
MoonlittStatus moonlitt_runtime_set_track_trim(struct RuntimeHandle *rt,
                                               int track_id,
                                               float trim_db);

/**
 * Track pan: 0.0 = hard left, 0.5 = centre, 1.0 = hard right.
 */
MoonlittStatus moonlitt_runtime_set_track_pan(struct RuntimeHandle *rt, int track_id, float pan);

/**
 * Mute (1) / unmute (0) a track.
 */
MoonlittStatus moonlitt_runtime_set_track_mute(struct RuntimeHandle *rt, int track_id, int mute);

/**
 * Solo (1) / unsolo (0) a track.
 */
MoonlittStatus moonlitt_runtime_set_track_solo(struct RuntimeHandle *rt, int track_id, int solo);

/**
 * Per-track send level into a send bus (linear gain).
 */
MoonlittStatus moonlitt_runtime_set_track_send(struct RuntimeHandle *rt,
                                               int track_id,
                                               int bus_id,
                                               float level);

/**
 * Route a track's output: `target_id` 0xFF (255) = master bus, any
 * other value = a group track id.
 */
MoonlittStatus moonlitt_runtime_set_track_route(struct RuntimeHandle *rt,
                                                int track_id,
                                                int target_id);

/**
 * Master bus volume (linear gain, 1.0 = unity).
 */
MoonlittStatus moonlitt_runtime_set_master_volume(struct RuntimeHandle *rt, float vol);

/**
 * Bypass (1) / engage (0) an insert effect on a track.
 */
MoonlittStatus moonlitt_runtime_set_insert_bypass(struct RuntimeHandle *rt,
                                                  int track_id,
                                                  int insert_id,
                                                  int bypass);

/**
 * Feed an insert's external sidechain from another track.
 * `source_track_id` -1 reverts to the internal sidechain.
 */
MoonlittStatus moonlitt_runtime_set_insert_sidechain(struct RuntimeHandle *rt,
                                                     int track_id,
                                                     int insert_id,
                                                     int source_track_id);

/**
 * Add a track at runtime. **Consumes** the backend out of
 * `engine_handle`. `channel_mask`: bit N = MIDI channel N (0xFFFF = all).
 * Returns the track id (>= 0), or a negative [`MoonlittStatus`].
 */
int moonlitt_runtime_add_track(struct RuntimeHandle *rt,
                               struct EngineHandle *engine_handle,
                               int channel_mask);

/**
 * Remove a track at runtime (notes are silenced first). Unknown ids
 * are ignored by the audio thread.
 */
MoonlittStatus moonlitt_runtime_remove_track(struct RuntimeHandle *rt, int track_id);

/**
 * Add an insert effect to a track at runtime. **Consumes** the backend.
 * Returns the insert id (>= 0), or a negative [`MoonlittStatus`].
 */
int moonlitt_runtime_add_insert(struct RuntimeHandle *rt,
                                int track_id,
                                struct EngineHandle *engine_handle);

/**
 * Remove an insert effect from a track at runtime. Unknown ids are
 * ignored by the audio thread.
 */
MoonlittStatus moonlitt_runtime_remove_insert(struct RuntimeHandle *rt,
                                              int track_id,
                                              int insert_id);

/**
 * Add a send bus at runtime. **Consumes** the backend. Returns the bus
 * id (>= 0), or a negative [`MoonlittStatus`].
 */
int moonlitt_runtime_add_send_bus(struct RuntimeHandle *rt, struct EngineHandle *engine_handle);

/**
 * List available MIDI input devices as JSON `[{"id","name"}, …]`.
 *
 * Ownership: caller frees with `moonlitt_free_string`. Returns NULL +
 * last-error when the MIDI subsystem is unavailable.
 */
char *moonlitt_runtime_list_midi_inputs(void);

/**
 * Start sequencer playback from the current position.
 */
MoonlittStatus moonlitt_runtime_play(struct RuntimeHandle *rt);

/**
 * Pause sequencer playback, keeping the position.
 */
MoonlittStatus moonlitt_runtime_pause(struct RuntimeHandle *rt);

/**
 * Stop sequencer playback and rewind to the start.
 * (The audio stream itself is controlled by
 * `moonlitt_runtime_start_audio` / `moonlitt_runtime_stop_audio`.)
 */
MoonlittStatus moonlitt_runtime_stop(struct RuntimeHandle *rt);

/**
 * Save the runtime's full session (mixer topology + plugin states +
 * transport) to a JSON file.
 *
 * NOT IMPLEMENTED YET — always returns `MOONLITT_ERR_UNSUPPORTED`.
 * Lands with ABI 1.0 (Phase 2 of the core-polish plan); the shape of
 * the signature is already final so bindings can prepare for it.
 */
MoonlittStatus moonlitt_runtime_save_session(struct RuntimeHandle *rt, const char *path);

/**
 * Create an 8-band parametric EQ engine.
 */
struct EngineHandle *moonlitt_builtin_create_eq(int sample_rate, int buffer_size);

/**
 * Create a dynamics compressor engine.
 */
struct EngineHandle *moonlitt_builtin_create_compressor(int sample_rate, int buffer_size);

/**
 * Create a stereo reverb engine (Dattorro plate algorithm).
 */
struct EngineHandle *moonlitt_builtin_create_reverb(int sample_rate, int buffer_size);

/**
 * Create a brickwall limiter engine with lookahead.
 */
struct EngineHandle *moonlitt_builtin_create_limiter(int sample_rate, int buffer_size);

/**
 * Create a noise gate / expander engine.
 */
struct EngineHandle *moonlitt_builtin_create_gate(int sample_rate, int buffer_size);

/**
 * Create a de-esser engine (sibilance reduction).
 */
struct EngineHandle *moonlitt_builtin_create_deesser(int sample_rate, int buffer_size);

/**
 * Create a stereo delay engine with tempo sync and ping-pong.
 */
struct EngineHandle *moonlitt_builtin_create_stereo_delay(int sample_rate, int buffer_size);

/**
 * Create a 4-voice chorus engine.
 */
struct EngineHandle *moonlitt_builtin_create_chorus(int sample_rate, int buffer_size);

/**
 * Create a through-zero flanger engine.
 */
struct EngineHandle *moonlitt_builtin_create_flanger(int sample_rate, int buffer_size);

/**
 * Create an N-stage allpass phaser engine.
 */
struct EngineHandle *moonlitt_builtin_create_phaser(int sample_rate, int buffer_size);

/**
 * Create a tremolo engine with tempo sync and stereo auto-pan.
 */
struct EngineHandle *moonlitt_builtin_create_tremolo(int sample_rate, int buffer_size);

/**
 * Create a gain utility engine (gain, polarity invert, mono sum).
 */
struct EngineHandle *moonlitt_builtin_create_gain(int sample_rate, int buffer_size);

/**
 * Create a stereo width processor engine (mid/side encoding).
 */
struct EngineHandle *moonlitt_builtin_create_stereo_width(int sample_rate, int buffer_size);

/**
 * Create a saturator engine (5 distortion models with oversampling).
 */
struct EngineHandle *moonlitt_builtin_create_saturator(int sample_rate, int buffer_size);

/**
 * Create a bitcrusher engine (sample-rate and bit-depth reduction).
 */
struct EngineHandle *moonlitt_builtin_create_bitcrusher(int sample_rate, int buffer_size);

/**
 * Create a multiband compressor engine (4-band crossover + per-band dynamics).
 */
struct EngineHandle *moonlitt_builtin_create_multiband_compressor(int sample_rate, int buffer_size);

/**
 * Create an auto-filter engine (LFO-modulated cutoff).
 */
struct EngineHandle *moonlitt_builtin_create_auto_filter(int sample_rate, int buffer_size);

/**
 * Create a pitch shifter engine (FFT-based frequency-domain shifting).
 */
struct EngineHandle *moonlitt_builtin_create_pitch_shifter(int sample_rate, int buffer_size);

/**
 * Create a convolution reverb engine from a mono WAV impulse response.
 *
 * * `ir_path` — UTF-8 path to a WAV (PCM-16/24/32 or float-32; only the
 *   first channel is used)
 * * `sample_rate` / `buffer_size` — as for the other factories (the
 *   buffer size determines FFT partition size and PDC latency)
 */
struct EngineHandle *moonlitt_builtin_create_convolver(const char *ir_path,
                                                       int sample_rate,
                                                       int buffer_size);

/**
 * Create a new Mixer for pre-building (tracks → sends → inserts →
 * `moonlitt_runtime_create_from_mixer`).
 *
 * Ownership: free with `moonlitt_mixer_destroy` unless consumed by
 * `moonlitt_runtime_create_from_mixer`.
 */
struct MixerHandle *moonlitt_mixer_create(int sample_rate, int buffer_size);

/**
 * Destroy a mixer handle. Safe to call with NULL. Only needed when the
 * mixer was NOT consumed by `moonlitt_runtime_create_from_mixer`.
 */
void moonlitt_mixer_destroy(struct MixerHandle *m);

/**
 * Add a track to a pre-built mixer. **Consumes** the backend out of
 * `engine_handle` (the empty handle must still be destroyed).
 *
 * * `channel_mask` — bitmask of MIDI channels this track responds to
 *   (bit N = channel N; 0xFFFF = all)
 *
 * Returns the track id (>= 0), or a negative [`MoonlittStatus`].
 */
int moonlitt_mixer_add_track(struct MixerHandle *m,
                             struct EngineHandle *engine_handle,
                             int channel_mask);

/**
 * Add a send bus to a pre-built mixer. **Consumes** the backend.
 * Returns the bus id (>= 0), or a negative [`MoonlittStatus`].
 */
int moonlitt_mixer_add_send_bus(struct MixerHandle *m, struct EngineHandle *engine_handle);

/**
 * Add an insert effect to a track of a pre-built mixer. **Consumes**
 * the backend. Returns the insert id (>= 0), or a negative
 * [`MoonlittStatus`] (`INVALID_ARG` when the track id is unknown).
 */
int moonlitt_mixer_add_insert(struct MixerHandle *m,
                              int track_id,
                              struct EngineHandle *engine_handle);

/**
 * Create a Runtime (live audio output) from a pre-built mixer.
 * **Consumes** the mixer on success. Returns NULL + last-error on
 * failure (e.g. no audio output device).
 */
struct RuntimeHandle *moonlitt_runtime_create_from_mixer(struct MixerHandle *m, int buffer_size);

/**
 * Create a 16-track mixer + live runtime from a single SF2 file: the
 * SF2 is loaded ONCE and each MIDI channel's track clones the font
 * (Arc-shared sample data, ~1× memory instead of 16×).
 *
 * Ownership: returns an owned RuntimeHandle* (free with
 * `moonlitt_runtime_destroy`), or NULL + last-error.
 */
struct RuntimeHandle *moonlitt_multitrack_create(const char *sf2_path,
                                                 int sample_rate,
                                                 int buffer_size);

/**
 * Load a session JSON file and build a Runtime from it. The returned
 * RuntimeHandle is in pre-started state — call
 * `moonlitt_runtime_start_audio` before expecting sound.
 *
 * Ownership: returns an owned RuntimeHandle* (free with
 * `moonlitt_runtime_destroy`), or NULL on failure (file missing,
 * schema mismatch, plug-in not found, state blob rejected, audio
 * device unavailable, …) with the reason in
 * `moonlitt_last_error_message()`.
 */
struct RuntimeHandle *moonlitt_session_load_from_file(const char *path, uint32_t buffer_size);

/**
 * Probe a session file without instantiating a Runtime. Returns
 * `MOONLITT_OK` when the file parses cleanly and matches the schema
 * version this build expects; `MOONLITT_ERR_STATE` (or
 * `MOONLITT_ERR_INVALID_ARG` for a bad path) otherwise. Useful as a
 * startup pre-flight check.
 */
MoonlittStatus moonlitt_session_validate_file(const char *path);

/**
 * Read a session file and return its canonical JSON text (useful for
 * inspection/debugging without building a runtime).
 *
 * Ownership: caller frees with `moonlitt_free_string`. Returns NULL +
 * last-error on failure.
 */
char *moonlitt_session_read_json(const char *path);

/**
 * Free a string previously returned by any `moonlitt_*` function that
 * documents "caller must free with `moonlitt_free_string`".
 */
void moonlitt_free_string(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MOONLITT_H */
