/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Opaque handle to an audio backend (instrument or effect).
 *
 * Created via `create()` or effect factory functions.
 * Consumed when passed to `Session.create()` or `Session.addTrack()`.
 */
export declare class Backend {
  /** Sample rate this backend was created with. */
  sampleRate(): number
  /** Number of controllable parameters. */
  paramCount(): number
  /** Set a parameter value. */
  setParam(id: number, value: number): void
  /** Get a parameter's current value. */
  getParam(id: number): number | null
  /**
   * Metadata for the parameter at the given index (0..param_count).
   * Returns None if the index is out of range or the backend has been consumed.
   */
  paramInfo(index: number): ParamInfo | null
  /** Human-readable display string for a parameter value (e.g., "+3.5 dB"). */
  paramDisplay(id: number, value: number): string | null
  /** Whether this backend has been consumed (passed to a Session). */
  isConsumed(): boolean
}

/**
 * Audio session — manages real-time playback, tracks, and mixing.
 *
 * Created from a `Backend` via `Session.create()`. The backend is consumed
 * and placed in a mixer as the primary track.
 */
export declare class Session {
  /**
   * Create a new session from an audio backend.
   *
   * The backend is consumed (moved into the internal mixer).
   * To add more instruments, use `addTrack()` afterward.
   */
  static create(backend: Backend, sampleRate: number, bufferSize: number): Session
  /** Start audio output (opens the system audio device). */
  start(): void
  /** Stop (pause) audio output. */
  stop(): void
  /** Begin transport playback. */
  play(): void
  /** Pause transport. */
  pause(): void
  /** Stop transport (resets to beginning). */
  stopPlayback(): void
  /** Whether the transport is currently playing. */
  isPlaying(): boolean
  /** Set tempo in BPM. */
  setTempo(bpm: number): void
  /** Enable or disable loop playback. */
  setLoop(enabled: boolean): void
  /**
   * Load a MIDI file. Sequencer takes effect on the next audio callback.
   * Transport state is unchanged — call `play()` to start playback.
   */
  loadMidi(path: string): void
  /** Remove any loaded MIDI sequence. */
  unloadMidi(): void
  /** Send MIDI note on. */
  noteOn(channel: number, note: number, velocity: number): void
  /** Send MIDI note off. */
  noteOff(channel: number, note: number): void
  /** Send MIDI CC (control change). */
  cc(channel: number, cc: number, value: number): void
  /** Send MIDI pitch bend. */
  pitchBend(channel: number, value: number): void
  /** Send MIDI program change. */
  programChange(channel: number, program: number): void
  /** Silence all active notes. */
  allNotesOff(): void
  /** Set master volume via MIDI event (0.0 to 1.0). */
  setVolume(volume: number): void
  /** Set a backend parameter by ID. */
  setParam(id: number, value: number): void
  /**
   * Add an instrument track. Returns the track ID.
   *
   * `channel_mask` is a 16-bit bitmask selecting MIDI channels (0xFFFF = all).
   */
  addTrack(backend: Backend, channelMask: number): number
  /** Remove a track by ID. */
  removeTrack(trackId: number): void
  /**
   * Replace a track's instrument while keeping the channel strip
   * (volume, pan, sends, inserts, meter) intact.
   */
  swapTrackBackend(trackId: number, backend: Backend): void
  /** Add an insert effect to a track. Returns the insert ID. */
  addInsert(trackId: number, effect: Backend): number
  /** Remove an insert effect from a track. */
  removeInsert(trackId: number, insertId: number): void
  /** Add a send bus with an effect. Returns the bus ID. */
  addSendBus(effect: Backend): number
  /** Set track volume (0.0 to 1.0). */
  setTrackVolume(trackId: number, volume: number): void
  /** Set track pan (-1.0 left, 0.0 center, 1.0 right). */
  setTrackPan(trackId: number, pan: number): void
  /** Set track trim in dB. */
  setTrackTrim(trackId: number, trimDb: number): void
  /** Mute or unmute a track. */
  setTrackMute(trackId: number, mute: boolean): void
  /** Solo or unsolo a track. */
  setTrackSolo(trackId: number, solo: boolean): void
  /** Set track send level to a bus. */
  setTrackSend(trackId: number, busId: number, level: number): void
  /** Set master bus volume. */
  setMasterVolume(volume: number): void
  /** Bypass or enable an insert effect. */
  setInsertBypass(trackId: number, insertId: number, bypass: boolean): void
  /** Route a track's output. `target_id` 0xFF = master, else group track ID. */
  setTrackRoute(trackId: number, targetId: number): void
  /**
   * Set external sidechain source for an insert effect.
   * `source_track_id` = None reverts to internal sidechain.
   */
  setInsertSidechain(trackId: number, insertId: number, sourceTrackId?: number | undefined | null): void
  /** Set a parameter on a track's backend. */
  setParamForTrack(trackId: number, paramId: number, value: number): void
  /** Set a parameter on a track's insert effect. */
  setInsertParam(trackId: number, insertId: number, paramId: number, value: number): void
  /** Set a parameter on a send bus effect. */
  setSendBusParam(busId: number, paramId: number, value: number): void
  /**
   * Read peak levels for a track (linear scale, 0.0 to 1.0+).
   * Returns { peakL, peakR }. Returns zeros if track ID is unknown.
   */
  trackLevels(trackId: number): TrackLevels
  /** Read peak levels for the master bus (linear scale, 0.0 to 1.0+). */
  masterLevels(): TrackLevels
  /** Number of tracks in the mixer. */
  trackCount(): number
  /** List available MIDI input devices. */
  static listMidiInputs(): Array<MidiDevice>
  /** Number of events dropped due to ring buffer overflow. */
  droppedEvents(): number
  /** Shutdown the session and release audio resources. */
  shutdown(): void
}

/**
 * Create an audio backend from a file path (.sf2, .vst3, .clap).
 *
 * Auto-detects format by file extension.
 */
export declare function create(path: string, sampleRate: number, bufferSize: number): Backend

/** Create an auto-filter with LFO-modulated cutoff. */
export declare function createAutoFilter(sampleRate: number): Backend

/** Create a bitcrusher (sample rate and bit depth reduction). */
export declare function createBitcrusher(sampleRate: number): Backend

/** Create a 4-voice chorus. */
export declare function createChorus(sampleRate: number): Backend

/** Create a dynamics compressor. */
export declare function createCompressor(sampleRate: number): Backend

/**
 * Create a convolution reverb from an impulse response buffer.
 *
 * `ir` contains the impulse response samples as f64 (converted to f32 internally).
 * `block_size` determines processing latency (typically 512 or 1024).
 */
export declare function createConvolver(ir: Array<number>, sampleRate: number, blockSize: number): Backend

/** Create a Dattorro plate reverb. */
export declare function createDattorroReverb(sampleRate: number): Backend

/** Create a de-esser (sibilance reduction). */
export declare function createDeesser(sampleRate: number): Backend

/** Create an 8-band parametric EQ. */
export declare function createEq(sampleRate: number): Backend

/** Create a through-zero flanger. */
export declare function createFlanger(sampleRate: number): Backend

/** Create a gain utility (gain, polarity invert, mono sum). */
export declare function createGain(sampleRate: number): Backend

/** Create a noise gate / expander. */
export declare function createGate(sampleRate: number): Backend

/** Create a brickwall limiter with lookahead. */
export declare function createLimiter(sampleRate: number): Backend

/** Create a multiband compressor (4-band crossover + per-band dynamics). */
export declare function createMultibandCompressor(sampleRate: number): Backend

/** Create an N-stage allpass phaser. */
export declare function createPhaser(sampleRate: number): Backend

/** Create a pitch shifter (FFT-based frequency-domain pitch shifting). */
export declare function createPitchShifter(sampleRate: number): Backend

/** Create a Freeverb reverb. */
export declare function createReverb(sampleRate: number): Backend

/** Create a saturator with 5 distortion models. */
export declare function createSaturator(sampleRate: number): Backend

/** Create a stereo delay with tempo sync and ping-pong. */
export declare function createStereoDelay(sampleRate: number): Backend

/** Create a stereo width processor (mid/side encoding). */
export declare function createStereoWidth(sampleRate: number): Backend

/** Create a tremolo with tempo sync and stereo auto-pan. */
export declare function createTremolo(sampleRate: number): Backend

/** Available MIDI input device. */
export interface MidiDevice {
  id: number
  name: string
}

/** Metadata for a single backend parameter. */
export interface ParamInfo {
  id: number
  name: string
  group: string
  min: number
  max: number
  default: number
  /** 0 = continuous, >0 = number of discrete steps. */
  stepCount: number
}

/** Discovered audio plugin metadata. */
export interface PluginInfo {
  name: string
  path: string
  format: string
}

/**
 * Scan system directories for available audio plugins (VST3, CLAP).
 *
 * Returns metadata for each discovered plugin.
 */
export declare function scanPlugins(sampleRate: number, bufferSize: number): Array<PluginInfo>

/** List file extensions the engine can load. */
export declare function supportedFormats(): Array<string>

/** Peak metering levels for a stereo channel. */
export interface TrackLevels {
  peakL: number
  peakR: number
}
